import { Inter } from "next/font/google";
import "./globals.css";
import Script from 'next/script'
import Header  from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-light dark:bg-dark dark:text-light `}>
        <Header />
        {children}
        <Script id='theme-switcher' strategy='beforeInteractive' >
          {`
            if(localStorage.theme==="dark"||(!("theme" in localStorage) && window.matchMedia("(prefDarkQuery)"))){
              document.documentElement.classList.add("dark")
            }else{
              document.documentElement.classList.remove("dark")
            }
          `}
        </Script>
        <script src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"></script>
      </body>
    </html>
  );
}
